### ISSUE TITLE
Messes with column spacing, interferes with the ability to drag columns

### ISSUE THREAD

**Issue by huachuman** [alima-webdev/zotero-article-status#8]
**Describe the bug**
Messes with column spacing, interferes with the ability to drag columns

**To Reproduce**
- enable the plugin

**Expected behavior**
it doesn't mess with the spacing

**Screenshots**
What it looks like with extension enabled:
![image](https://github.com/user-attachments/assets/c7d6b146-c7d6-49af-bd70-5216b3f4ed5b)

When disabled:
![image](https://github.com/user-attachments/assets/53db54b7-3724-4b79-b7ec-02a563508de9)

**Desktop (please complete the following information):**

-   OS: [e.g. iOS] - Windows 11
-   Browser [e.g. chrome, safari] - you didn't fix the template did you
-   Zotero version [e.g. 22] - 7.0.8

**Comment by huachuman** [comment]
Weird dragging behavior 

![GIF 10-29-2024 7-40-21 AM](https://github.com/user-attachments/assets/bad1814f-b1e0-463e-aac6-72a9ae5eb3fb)

Seems like just the date dragging is messed up.

**Comment by alima-webdev** [comment]
Thank you for pointing that out. It should be fixed in the latest update v1.0.5

**Comment by huachuman** [comment]
I cannot confirm that the dragging is caused by this plugin. But the spacing, yes.

**Comment by itsameWolf** [comment]
resizing columns is still broken for me, it resize the column next to it in the opposite direction.
